name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o go-fiber-api ./cmd/server

    - uses: actions/upload-artifact@v4
      with:
        name: go-fiber-api
        path: ./go-fiber-api
